### ISSUE TITLE
It is not working for proton 5.13

### ISSUE THREAD

**Issue by jcnils** [aoleg94/protonhax#1]
I need to debug some more, I don't know how to debug the "init" part.

but the problem is that when we call `run` on Proton 5.13 the call is something like:

`
/usr/bin/envload /run/user/7890/protonhax/12345/env /home/you/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point run /home/you/Program.exe`

instead of 
`/usr/bin/envload /run/user/7890/protonhax/12345/env /home/you/SteamLibrary/steamapps/common/Proton\ 5.13/proton run /home/you/Program.exe`

I need to figure out why it is getting `SteamLinuxRuntime_soldier/_v2-entry-point` instead of Proton version

**Comment by aoleg94** [comment]
Please go to upstream repo https://gitlab.com/xaryphon/protonhax and post your issue there, I am not a maintainer of protonhax.

**Comment by jcnils** [comment]
I have no access there.

404 not found :(

**Comment by aoleg94** [comment]
>`SteamLinuxRuntime_soldier/_v2-entry-point`

well that has to be something with new steam runtime in proton 5.13, valve has modified it a lot since 5.10.

**Comment by aoleg94** [comment]
Insert this after first line, this will redirect execution trace and all output to /tmp/protonhax.*.log. Use this to trace and debug the "init" part.

```bash
set -x
exec >/tmp/protonhax.$$.log 2>&1
```

**Comment by jcnils** [comment]
Thank you very much @aoleg94 

The problem with 5.13 is that the argument is longer, something like this:

`echo /home/me/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --deploy=soldier --suite=soldier --verb=waitforexitandrun -- /home/me/SteamLibrary/steamapps/common/Proton 5.13/proton waitforexitandrun /home/me/SteamLibrary/steamapps/common/Game/game.exe`

And it used to be like this: 

`/home/me/SteamLibrary/steamapps/common/Proton 5.0/proton waitforexitandrun /home/me/SteamLibrary/steamapps/common/Rover Mechanic Simulator/rms.exe`

I could probably could solve it for all proton versions by getting the second last argument.

I saw that the maintainer of gitlab is the same of the Arch User Repo. I posted there as well.
Once I get it working on my machine I will post the code there (and here).


I am also getting a bunch of errors like this, but it would be for another thread/repo.
`ERROR: ld.so: object '/home/me/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

**Comment by jcnils** [comment]
Thank you very much for helping me figuring out the problem. Xaryphon answered in the AUR package thread. I will be fixing the repo there soon.
